[application]

# App (Project) Name
name = "sudoku-solver"

[web.app]

# HTML title tag content
title = "sudoku-solver"

# include `assets` in web platform
[web.resource]

# CSS style file

style = []

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
